home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path('', views.home, name='home'),
    path('submit/', views.submit, name='submit'),
    path('result/', views.result, name='result'),
]

shipping/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls'), name = "index"),
    path('admin', admin.site.urls, name = "submit"),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from home.choices import *

class InfoForm(forms.Form):
   #sender = forms.CharField(max_length = 100, label = "Name")
   sender_address_1 = forms.CharField(help_text="Street Address, Etc.", max_length = 100, label = "Address")
   sender_address_2 = forms.CharField(help_text="Apartment, Suite, Unit, Etc. (Optional)", max_length = 100, label = "", required=False)
   sender_city = forms.CharField(max_length = 100, label = "City")
   sender_state = forms.CharField(max_length = 100, label = "State")
   sender_zip_code = forms.CharField(max_length = 100, label="Zip Code")
   sender_country = forms.ChoiceField(choices=ISO3166, label="Country")

   #recipient = forms.CharField(max_length=100, label="Name")
   recipient_address_1 = forms.CharField(help_text="Street Address, Etc.", max_length = 100, label = "Address")
   recipient_address_2 = forms.CharField(help_text="Apartment, Suite, Unit, Etc. (Optional)", max_length=100, label="", required=False)
   recipient_city = forms.CharField(max_length = 100, label = "City")
   recipient_state = forms.CharField(max_length = 100, label = "State")
   recipient_zip_code = forms.CharField(max_length = 100, label="Zip Code")
   recipient_country = forms.ChoiceField(choices=ISO3166, label="Country")
   recipient_resident = forms.BooleanField(label="Check if this is a residential address", required=False)
   height = forms.IntegerField(min_value=1)
   width = forms.IntegerField(min_value=1)
   length = forms.IntegerField(min_value=1)
   weight = forms.IntegerField(min_value=1)
   unit = forms.ChoiceField(choices=weightUnits)

   def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)
      #self.fields["sender_state"] = forms.ChoiceField(choices=get_countries(), label="Country")
      #self.fields["recipient_state"] = forms.ChoiceField(choices=ISO3166, label="Country")


#class ResultForm(forms.Form):

home/controllers/home_controller.py
from ..network.Shipping_Utilities import Shipping_Utilities

class HomeController():
    def validate_data(self, req):
        ship_utils = Shipping_Utilities()
        validate_ret = ship_utils.validate_address(req)
        #print(validate_ret)
        return validate_ret
    def get_all_rates(self, req):
        ship_utils = Shipping_Utilities()
        return ship_utils.get_rates(req)

home/views.py
import urllib

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .controllers.home_controller import HomeController
from .forms import InfoForm


def home(request):
    form = InfoForm()
    return render(request, 'home/home.html', {'form': form})


def submit(request):
    def request_to_dict(req):
        ret = {i: req.POST[i] for i in req.POST}
        if "recipient_resident" not in ret:
            ret["recipient_resident"] = False
        return ret
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = InfoForm(request.POST)
        #print(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            home_controller = HomeController()

            info_dict = request_to_dict(request)
            print(info_dict)
            validate_check = home_controller.validate_data(info_dict)
            #print(validate_check)
            if validate_check["sender"][1] == [] and validate_check["recipient"][1] == []:
                rates = home_controller.get_all_rates(info_dict)
                #print(rates)
                request.session['resp'] = rates
                return HttpResponseRedirect(reverse('home:result'))

    else:
        form = InfoForm()
    #print(form)
    #print(unitChoiceForm)
    error_message = {}
    if validate_check["recipient"][1] != []:
        errors = validate_check["recipient"][1]
        for i in range(len(errors)):
            error_message["Recipient Address Error"] = \
                error_message.setdefault("Recipient Address Error", [])\
                +[validate_check["recipient"][1][i]["message"]]
    if validate_check["sender"][1] != []:
        errors = validate_check["sender"][1]
        for i in range(len(errors)):
            error_message["Sender Address Error"] = \
                error_message.setdefault("Sender Address Error", [])\
                +[validate_check["sender"][1][i]["message"]]

    print(error_message)
    return render(request, 'home/home.html', {'form': form, "error_message": error_message})

def result(request):
    resp = request.session.get('resp')
    return render(request, 'home/result.html', {"resp":resp})

home/templates/home/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>shipping helper</title>
</head>
<body>
    {% load crispy_forms_tags %}
    {% if error_message %}
        {% for key,errors in error_message.items %}
            <div class="alert alert-danger alert-dismissible">
                <p><strong>{{key}}:</strong></p>
                {% for error in errors %}
                    <p>{{error}}</p>
                {% endfor %}
            </div>
        {% endfor %}
    {% endif %}

    {% block content %}
    <form action = "{% url 'home:submit' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-sm-6 mb-0 sender">
              <h2>Sender</h2>
              {{ form.sender_address_1|as_crispy_field }}
              {{ form.sender_address_2|as_crispy_field }}
              {{ form.sender_city|as_crispy_field }}
              {{ form.sender_zip_code|as_crispy_field }}
              <div class="form-row">
                  <div class="form-group col-sm-6 mb-0">
                      {{ form.sender_country|as_crispy_field }}
                  </div>
                  <div class="form-group col-sm-6 mb-0">
                      {{ form.sender_state|as_crispy_field }}
                  </div>
              </div>
          </div>
          <div class="form-group col-sm-6 mb-0">
              <h2>Recipient</h2>
              {{ form.recipient_address_1|as_crispy_field }}
              {{ form.recipient_address_2|as_crispy_field }}
              {{ form.recipient_city|as_crispy_field }}
              {{ form.recipient_zip_code|as_crispy_field }}
              <div class="form-row">
                  <div class="form-group col-sm-6 mb-0">
                      {{ form.recipient_country|as_crispy_field }}
                  </div>
                  <div class="form-group col-sm-6 mb-0">
                      {{ form.recipient_state|as_crispy_field }}
                  </div>
              </div>
              {{form.recipient_resident|as_crispy_field}}
          </div>

        </div>
        <h2>Dimensions</h2>
        <div class="form-row">
          <div class="form-group col-sm-4 mb-0">
            {{ form.height|as_crispy_field }}
          </div>
          <div class="form-group col-sm-4 mb-0">
            {{ form.width|as_crispy_field }}
          </div>
          <div class="form-group col-sm-4 mb-0">
            {{ form.length|as_crispy_field }}
          </div>
        </div>
        {{ form.weight|as_crispy_field }}
        {{ form.unit|as_crispy_field }}

      <input class="btn btn-primary" type="submit" value="Submit">
    </form>
    {% endblock %}

</body>
</html>

home/templates/home/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
<h1>Results</h1>
{% for key,cour in resp.items %}
    <h2>{{key}}</h2>
    {% for rate in cour %}
        {% for prices_key,prices in rate.items %}
            <table class="table table-striped">
            <thead>
              <tr>
                  <th></th>
                  {% for price_type,price_value in prices.items %}
                    <th>{{price_type}}</th>
                  {% endfor %}
              </tr>
            </thead>
            <tbody>
              <tr>
                  <td>{{prices_key}}</td>
                  {% for price_type,price_value in prices.items %}
                    <td>{{price_value}}</td>
                  {% endfor %}
              </tr>
            </tbody>
            </table>
        {% endfor %}
    {% endfor %}
{% endfor %}


</body>
</html>